[package]
name = "tygr-derive"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Derive macros for tygr — do not depend on this directly."
repository = "https://github.com/intersystems-community/tygr"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
either = "1.15.0"

[features]
default = []
trace = ["trace_pos"]
trace_pos = []
lower_bnf_name = []
upper_bnf_name = []
